version: '2'
services:
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: melynx-bot
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3308:3306'
  melynxbot:
    build: .
    ports:
      - '80:7777'
    depends_on:
      - mysql
    command: ['node', '-r', 'esm', 'index.js']
