version: "2"
services:
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: melynx-bot
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
