version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: melynx
      POSTGRES_PASSWORD: password # Replace this with an actual password.
    ports:
      - '5432:5432'
